# Generated by Django 2.0.6 on 2019-02-21 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pageNumber', models.IntegerField()),
                ('genre', models.CharField(max_length=30)),
                ('publishDate', models.DateField(default=datetime.datetime(2019, 2, 21, 17, 30, 21, 668642, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
