# Generated by Django 2.0.6 on 2019-02-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwApp', '0004_auto_20190221_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishDate',
            field=models.DateField(),
        ),
    ]
